spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bootstart?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: constGGG4412
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: root
    password: root123
server:
  port: 9090
  servlet:
    context-path: /boot
nacos:
    config:
      server-addr: 127.0.0.1:8848
    discovery:
      server-addr: 127.0.0.1:8848
